---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-master-disable-lldp-agent
spec:
  config:
    ignition:
      config:
        replace:
          verification: {}
      proxy: {}
      security:
        tls: {}
      timeouts: {}
      version: 3.2.0
    passwd: {}
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,IyEvdXNyL2Jpbi9lbnYgYmFzaAoKZm9yIGkgaW4gZW5zMWYwIGVuczFmMSBlbnMxZjIgZW5zMWYzIGVuczJmMCBlbnMyZjEgZW5zMmYyIGVuczJmMzsgZG8KICBldGh0b29sIC0tc2V0LXByaXYtZmxhZ3MgJGkgZnctbGxkcC1hZ2VudCBvZmYKZG9uZQo=
            verification: {}
          group: {}
          mode: 0550
          path: /usr/local/bin/disable-lldp-agent.sh
          user: {}
    systemd:
      units:
        - contents: |
            [Unit]
            Description==Disable LLDP agent

            [Service]
            Type=oneshot
            ExecStart=/usr/local/bin/disable-lldp-agent.sh

            [Install]
            WantedBy=multi-user.target
          enabled: true
          name: disable-lldp-agent.service
