apiVersion: batch/v1
kind: Job
metadata:
  name: e810-fw-upgrade-job-420-ens1
spec:
  template:
    spec:
      initContainers:
        - name: init
          image: "hub-helper:5000/e810-fw-devlink:4.20"
          imagePullPolicy: IfNotPresent
          command: ["rpm-ostree", "usroverlay"]
      containers:
        - name: nvmupdate
          image: "hub-helper:5000/e810-fw-devlink:4.20"
          imagePullPolicy: Always
          command: ["/bin/bash", "-x", "/E810/Linux_x64/devlink.sh", "ens1f0"]
      securityContext:
        privileged: true
      hostNetwork: true
      restartPolicy: Never