apiVersion: batch/v1
kind: Job
metadata:
  name: e810-fw-upgrade-job-420-ens1
spec:
  template:
    spec:
      containers:
        - name: nvmupdate
          image: "quay.io/bzhai/e810-devlink:4.20"
          imagePullPolicy: IfNotPresent
          command: ["/E810/Linux_x64/devlink.sh" "ens1f0"]
      restartPolicy: Never