apiVersion: batch/v1
kind: Job
metadata:
  namespace: intel-fw
  name: e810-fw-upgrade-job-420-ens2
spec:
  template:
    spec:
      containers:
        - name: devlink
          image: "quay.io/bzhai/e810-fw-devlink:4.20"
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
              - SYS_CHROOT
              - CAP_SYS_ADMIN
            runAsGroup: 0
            runAsUser: 0
          command: ["/bin/bash", "-x", "-c"]
          args:
            - /host/sbin/chroot /host /bin/bash -c "/E810/Linux_x64/upgrade-fw.sh ens2f0";
          volumeMounts:
           - mountPath: /host
             name: rootfs
      serviceAccountName: sa-fw-upgrade
      securityContext:
        fsGroup: 0
      hostNetwork: true
      hostPID: true
      restartPolicy: Never
      volumes:
        - hostPath:
            path: /
            type: ""
          name: rootfs
